### ISSUE TITLE
Magisterium mod

### ISSUE THREAD

**Issue by Avalon-Quin** [Reoseah/magisterium#1]
I love this mod, but i want to use it with this other mod, but it keeps crashing my game, i was wondering if you could make the file smaller so i can use it with other mods plsssss!

**Comment by reoseah** [comment]
Please include crash log(s) and what other mods are you trying to use, so I can recreate and solve this problem.

**Comment by Avalon-Quin** [comment]
Ok im trying to use it with the Svm superpower mod

**Comment by Avalon-Quin** [comment]
and here's the crash log [image: Screenshot 2024-11-04 161938.png]    [image:
Screenshot 2024-11-04 162120.png]
[image: Screenshot 2024-11-04 162134.png]
[image: Screenshot 2024-11-04 162154.png]
[image: Screenshot 2024-11-04 162235.png]
[image: Screenshot 2024-11-04 162312.png]
[image: Screenshot 2024-11-04 162348.png]
[image: Screenshot 2024-11-04 162421.png]
[image: Screenshot 2024-11-04 162433.png]

**Comment by Avalon-Quin** [comment]
and here's is the copy and pasted version   




java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'magisterium' at 'io.github.reoseah.magisterium.Magisterium'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at knot//net.minecraft.class_310.<init>(class_310.java:482)
	at knot//net.minecraft.client.main.Main.main(Main.java:248)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_2753
	at knot//io.github.reoseah.magisterium.Magisterium.onInitialize(Magisterium.java:57)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2753
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 8 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at knot//net.minecraft.class_310.<init>(class_310.java:482)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22621.3593 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22621.4036 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22621.4036 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22621.4249 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.24090.11 (26d75470953920f90fd0438874501e9d9a31e621):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		POWRPROF.dll:Power Profile Helper DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.22621.4249 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.4317 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		extnet.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22621.4317 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		javaw.exe:OpenJDK Platform binary:21.0.3.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		jli.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		jna4312674302759704164.dll:JNA native library:7.0.0:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:21.0.3.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.22621.3958 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		mc-sec-plugin-x64.dll:McAfee Antivirus Core Plugin:1.3.1303.0:McAfee, LLC
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		nio.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.4249 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer DLL:10.0.22621.4249 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22621.4111 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.3593 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		win32u.dll:Win32u:10.0.22621.4317 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows Base Types DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.3958 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
Stacktrace:
	at knot//net.minecraft.client.main.Main.main(Main.java:248)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.21.2
	Minecraft Version ID: 1.21.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 248138880 bytes (236 MiB) / 402653184 bytes (384 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-1240P
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.11
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 16
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.101.1999
	Memory slot #0 capacity (MiB): 2048.00
	Memory slot #0 clockSpeed (GHz): 6.40
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 2048.00
	Memory slot #1 clockSpeed (GHz): 6.40
	Memory slot #1 type: Unknown
	Memory slot #2 capacity (MiB): 2048.00
	Memory slot #2 clockSpeed (GHz): 6.40
	Memory slot #2 type: Unknown
	Memory slot #3 capacity (MiB): 2048.00
	Memory slot #3 clockSpeed (GHz): 6.40
	Memory slot #3 type: Unknown
	Memory slot #4 capacity (MiB): 2048.00
	Memory slot #4 clockSpeed (GHz): 6.40
	Memory slot #4 type: Unknown
	Memory slot #5 capacity (MiB): 2048.00
	Memory slot #5 clockSpeed (GHz): 6.40
	Memory slot #5 type: Unknown
	Memory slot #6 capacity (MiB): 2048.00
	Memory slot #6 clockSpeed (GHz): 6.40
	Memory slot #6 type: Unknown
	Memory slot #7 capacity (MiB): 2048.00
	Memory slot #7 clockSpeed (GHz): 6.40
	Memory slot #7 type: Unknown
	Virtual memory max (MiB): 32450.86
	Virtual memory used (MiB): 11092.69
	Swap memory total (MiB): 16384.00
	Swap memory used (MiB): 88.57
	Space in storage for jna.tmpdir (MiB): available: 259306.38, total: 487598.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 259306.38, total: 487598.00
	Space in storage for io.netty.native.workdir (MiB): available: 259306.38, total: 487598.00
	Space in storage for java.io.tmpdir (MiB): available: 259306.38, total: 487598.00
	Space in storage for workdir (MiB): available: 259306.38, total: 487598.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.106.1+1.21.2
			fabric-api-base: Fabric API Base 0.4.48+c47b9d4373
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.78+c47b9d4373
			fabric-biome-api-v1: Fabric Biome API (v1) 14.0.5+c47b9d4373
			fabric-block-api-v1: Fabric Block API (v1) 1.0.28+c47b9d4373
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.16+c47b9d4373
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.2+c47b9d4373
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.22+c47b9d4373
			fabric-command-api-v1: Fabric Command API (v1) 1.2.56+f71b366f73
			fabric-command-api-v2: Fabric Command API (v2) 2.2.35+c47b9d4373
			fabric-commands-v0: Fabric Commands (v0) 0.2.73+df3654b373
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.5+c47b9d4373
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.0+7f945d5b73
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.0+c47b9d4373
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.3+c47b9d4373
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.38+c47b9d4373
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 21.0.14+c47b9d4373
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.7+c47b9d4373
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.5+c47b9d4373
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 2.0.9+c47b9d4373
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.59+c47b9d4373
			fabric-item-api-v1: Fabric Item API (v1) 11.1.5+c47b9d4373
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.15+e7c9ab6673
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.53+c47b9d4373
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.51+df3654b373
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.22+c47b9d4373
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.24+3f89f5a573
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.12+c47b9d4373
			fabric-message-api-v1: Fabric Message API (v1) 6.0.19+c47b9d4373
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 3.0.7+c47b9d4373
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.3+56ec7ac673
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 17.0.7+c47b9d4373
			fabric-particles-v1: Fabric Particles (v1) 4.0.8+c47b9d4373
			fabric-recipe-api-v1: Fabric Recipe API (v1) 7.0.2+c47b9d4373
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.0+56ec7ac673
			fabric-renderer-api-v1: Fabric Renderer API (v1) 4.0.3+c47b9d4373
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.9.3+c47b9d4373
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.54+73761d2e73
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.13+c47b9d4373
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.81+df3654b373
			fabric-rendering-v1: Fabric Rendering (v1) 8.0.5+c47b9d4373
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.8+c47b9d4373
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.5+c47b9d4373
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.32+c47b9d4373
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.98+c47b9d4373
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.29+c47b9d4373
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.0+c47b9d4373
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.8+c47b9d4373
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		java: OpenJDK 64-Bit Server VM 21
		magisterium: Magisterium 0.0.5
		minecraft: Minecraft 1.21.2
		mr_svm_powers: Super Powers 1.611
	Launched Version: fabric-loader-0.16.9-1.21.2
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GFLW Platform: <error>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: <unknown>

**Comment by reoseah** [comment]
Ok, thanks for the collaboration! 

So far, my guess is that I made the mod for version 1.21.1, and it should not have been marked for 1.21.2 and above (which happened automatically on upload to Modrinth and I didn't unselect it). In any case, thank you for providing additional details!

**Comment by reoseah** [comment]
Indeed it crashes on 1.21.2, I have went through all versions on Modrinth and unmarked versions other than 1.21.1 for now

**Comment by reoseah** [comment]
Oh dear I wasn't working on mods lately and wasn't aware how much changes there are between these two minor versions... I will port it, eventually, for now you can play it on 1.21.1, and sorry for the inconvenience

**Comment by Avalon-Quin** [comment]
Ok thanks for taking the time out of your day to actually respond to my issue, but i have a question, you dont have to answer it, but do  you ever thing the Magisterium mod will ever be on 1.21.2 like ever. 😶‍🌫️

**Comment by reoseah** [comment]
https://modrinth.com/mod/magisterium/version/TTxP1bXj
